services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # ubah ke 8001 supaya ga bentrok sama Odoo
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mjhotel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hotelmj
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80" # ubah ke 8081 supaya ga bentrok sama pgAdmin

volumes:
  db_data:
